export type BrazilLocationSuggestion = {
  city: string;
  label: string;
  state: string;
};

export const brazilLocationSuggestions: BrazilLocationSuggestion[] = [
  { label: "Aclimacao", city: "São Paulo", state: "SP" },
  { label: "Bela Vista", city: "São Paulo", state: "SP" },
  { label: "Brooklin", city: "São Paulo", state: "SP" },
  { label: "Itaim Bibi", city: "São Paulo", state: "SP" },
  { label: "Jardins", city: "São Paulo", state: "SP" },
  { label: "Lapa", city: "São Paulo", state: "SP" },
  { label: "Moema", city: "São Paulo", state: "SP" },
  { label: "Morumbi", city: "São Paulo", state: "SP" },
  { label: "Pinheiros", city: "São Paulo", state: "SP" },
  { label: "Tatuapé", city: "São Paulo", state: "SP" },
  { label: "Vila Mariana", city: "São Paulo", state: "SP" },
  { label: "Vila Olímpia", city: "São Paulo", state: "SP" },
  { label: "Savassi", city: "Belo Horizonte", state: "MG" },
  { label: "Funcionários", city: "Belo Horizonte", state: "MG" },
  { label: "Lourdes", city: "Belo Horizonte", state: "MG" },
  { label: "Pampulha", city: "Belo Horizonte", state: "MG" },
  { label: "Buritis", city: "Belo Horizonte", state: "MG" },
  { label: "Centro", city: "Belo Horizonte", state: "MG" },
  { label: "Boa Viagem", city: "Recife", state: "PE" },
  { label: "Casa Forte", city: "Recife", state: "PE" },
  { label: "Graças", city: "Recife", state: "PE" },
  { label: "Pina", city: "Recife", state: "PE" },
  { label: "Espinheiro", city: "Recife", state: "PE" },
  { label: "Madalena", city: "Recife", state: "PE" },
  { label: "Copacabana", city: "Rio de Janeiro", state: "RJ" },
  { label: "Ipanema", city: "Rio de Janeiro", state: "RJ" },
  { label: "Leblon", city: "Rio de Janeiro", state: "RJ" },
  { label: "Barra da Tijuca", city: "Rio de Janeiro", state: "RJ" },
  { label: "Botafogo", city: "Rio de Janeiro", state: "RJ" },
  { label: "Tijuca", city: "Rio de Janeiro", state: "RJ" },
  { label: "Lapa", city: "Rio de Janeiro", state: "RJ" },
  { label: "Méier", city: "Rio de Janeiro", state: "RJ" },
  { label: "Pituba", city: "Salvador", state: "BA" },
  { label: "Barra", city: "Salvador", state: "BA" },
  { label: "Ondina", city: "Salvador", state: "BA" },
  { label: "Rio Vermelho", city: "Salvador", state: "BA" },
  { label: "Itaigara", city: "Salvador", state: "BA" },
  { label: "Caminho das Árvores", city: "Salvador", state: "BA" },
  { label: "Aldeota", city: "Fortaleza", state: "CE" },
  { label: "Meireles", city: "Fortaleza", state: "CE" },
  { label: "Papicu", city: "Fortaleza", state: "CE" },
  { label: "Cocó", city: "Fortaleza", state: "CE" },
  { label: "Benfica", city: "Fortaleza", state: "CE" },
  { label: "Praia de Iracema", city: "Fortaleza", state: "CE" },
  { label: "Asa Sul", city: "Brasília", state: "DF" },
  { label: "Asa Norte", city: "Brasília", state: "DF" },
  { label: "Lago Sul", city: "Brasília", state: "DF" },
  { label: "Lago Norte", city: "Brasília", state: "DF" },
  { label: "Águas Claras", city: "Brasília", state: "DF" },
  { label: "Sudoeste", city: "Brasília", state: "DF" },
  { label: "Batel", city: "Curitiba", state: "PR" },
  { label: "Água Verde", city: "Curitiba", state: "PR" },
  { label: "Bigorrilho", city: "Curitiba", state: "PR" },
  { label: "Centro Cívico", city: "Curitiba", state: "PR" },
  { label: "Santa Felicidade", city: "Curitiba", state: "PR" },
  { label: "Boqueirão", city: "Curitiba", state: "PR" },
  { label: "Moinhos de Vento", city: "Porto Alegre", state: "RS" },
  { label: "Bela Vista", city: "Porto Alegre", state: "RS" },
  { label: "Menino Deus", city: "Porto Alegre", state: "RS" },
  { label: "Petrópolis", city: "Porto Alegre", state: "RS" },
  { label: "Cidade Baixa", city: "Porto Alegre", state: "RS" },
  { label: "Três Figueiras", city: "Porto Alegre", state: "RS" },
  { label: "Jurerê", city: "Florianópolis", state: "SC" },
  { label: "Centro", city: "Florianópolis", state: "SC" },
  { label: "Trindade", city: "Florianópolis", state: "SC" },
  { label: "Campeche", city: "Florianópolis", state: "SC" },
  { label: "Ingleses", city: "Florianópolis", state: "SC" },
  { label: "Lagoa da Conceição", city: "Florianópolis", state: "SC" },
  { label: "Adrianópolis", city: "Manaus", state: "AM" },
  { label: "Vieiralves", city: "Manaus", state: "AM" },
  { label: "Ponta Negra", city: "Manaus", state: "AM" },
  { label: "Centro", city: "Manaus", state: "AM" },
  { label: "Cidade Nova", city: "Manaus", state: "AM" },
  { label: "Parque Dez", city: "Manaus", state: "AM" },
  { label: "Umarizal", city: "Belém", state: "PA" },
  { label: "Nazaré", city: "Belém", state: "PA" },
  { label: "Marco", city: "Belém", state: "PA" },
  { label: "Batista Campos", city: "Belém", state: "PA" },
  { label: "Pedreira", city: "Belém", state: "PA" },
  { label: "Campina", city: "Belém", state: "PA" },
  { label: "Setor Bueno", city: "Goiânia", state: "GO" },
  { label: "Marista", city: "Goiânia", state: "GO" },
  { label: "Jardim Goiás", city: "Goiânia", state: "GO" },
  { label: "Setor Oeste", city: "Goiânia", state: "GO" },
  { label: "Campinas", city: "Goiânia", state: "GO" },
  { label: "Centro", city: "Goiânia", state: "GO" },
  { label: "Ponta Verde", city: "Maceió", state: "AL" },
  { label: "Jatiúca", city: "Maceió", state: "AL" },
  { label: "Mangabeiras", city: "Maceió", state: "AL" },
  { label: "Farol", city: "Maceió", state: "AL" },
  { label: "Cruz das Almas", city: "Maceió", state: "AL" },
  { label: "Centro", city: "Maceió", state: "AL" },
  { label: "Tambaú", city: "João Pessoa", state: "PB" },
  { label: "Manaíra", city: "João Pessoa", state: "PB" },
  { label: "Bessa", city: "João Pessoa", state: "PB" },
  { label: "Cabo Branco", city: "João Pessoa", state: "PB" },
  { label: "Altiplano", city: "João Pessoa", state: "PB" },
  { label: "Centro", city: "João Pessoa", state: "PB" },
  { label: "Ponta Negra", city: "Natal", state: "RN" },
  { label: "Lagoa Nova", city: "Natal", state: "RN" },
  { label: "Petrópolis", city: "Natal", state: "RN" },
  { label: "Tirol", city: "Natal", state: "RN" },
  { label: "Capim Macio", city: "Natal", state: "RN" },
  { label: "Centro", city: "Natal", state: "RN" },
  { label: "Atalaia", city: "Aracaju", state: "SE" },
  { label: "Jardins", city: "Aracaju", state: "SE" },
  { label: "13 de Julho", city: "Aracaju", state: "SE" },
  { label: "Farolândia", city: "Aracaju", state: "SE" },
  { label: "Grageru", city: "Aracaju", state: "SE" },
  { label: "Centro", city: "Aracaju", state: "SE" },
  { label: "Centro", city: "Campo Grande", state: "MS" },
  { label: "Jardim dos Estados", city: "Campo Grande", state: "MS" },
  { label: "Santa Fé", city: "Campo Grande", state: "MS" },
  { label: "Chácara Cachoeira", city: "Campo Grande", state: "MS" },
  { label: "Tiradentes", city: "Campo Grande", state: "MS" },
  { label: "Vila Planalto", city: "Campo Grande", state: "MS" },
  { label: "Duque de Caxias", city: "Cuiabá", state: "MT" },
  { label: "Goiabeiras", city: "Cuiabá", state: "MT" },
  { label: "Jardim das Américas", city: "Cuiabá", state: "MT" },
  { label: "Santa Rosa", city: "Cuiabá", state: "MT" },
  { label: "Centro Norte", city: "Cuiabá", state: "MT" },
  { label: "CPA", city: "Cuiabá", state: "MT" },
  { label: "Centro", city: "São Luís", state: "MA" },
  { label: "Ponta d'Areia", city: "São Luís", state: "MA" },
  { label: "Renascença", city: "São Luís", state: "MA" },
  { label: "Cohama", city: "São Luís", state: "MA" },
  { label: "Calhau", city: "São Luís", state: "MA" },
  { label: "Olho d'Água", city: "São Luís", state: "MA" },
  { label: "Plano Diretor Sul", city: "Palmas", state: "TO" },
  { label: "Plano Diretor Norte", city: "Palmas", state: "TO" },
  { label: "Taquaralto", city: "Palmas", state: "TO" },
  { label: "Jardim Aureny III", city: "Palmas", state: "TO" },
  { label: "Arso 24", city: "Palmas", state: "TO" },
  { label: "Arse 12", city: "Palmas", state: "TO" },
].sort((left, right) => {
  const leftText = `${left.label} ${left.city} ${left.state}`;
  const rightText = `${right.label} ${right.city} ${right.state}`;
  return leftText.localeCompare(rightText, "pt-BR");
});
