export const saoPauloNeighborhoods = [
  "Aclimacao",
  "Alto da Boa Vista",
  "Alto de Pinheiros",
  "Bela Vista",
  "Belém",
  "Bom Retiro",
  "Brooklin",
  "Butantã",
  "Campo Belo",
  "Campo Grande",
  "Capao Redondo",
  "Carrão",
  "Casa Verde",
  "Cerqueira César",
  "Chacara Klabin",
  "Cidade Ademar",
  "Cidade Dutra",
  "Cidade Jardim",
  "Consolação",
  "Cursino",
  "Freguesia do Ó",
  "Grajaú",
  "Higienópolis",
  "Indianópolis",
  "Ipiranga",
  "Itaim Bibi",
  "Itaquera",
  "Jabaquara",
  "Jaguaré",
  "Jardim América",
  "Jardim Anália Franco",
  "Jardim Europa",
  "Jardim Paulista",
  "Jardins",
  "Jardim São Luis",
  "Jardim Umarizal",
  "Lapa",
  "Liberdade",
  "Limão",
  "Moema",
  "Mooca",
  "Morumbi",
  "Parada Inglesa",
  "Paraisópolis",
  "Pari",
  "Perdizes",
  "Pinheiros",
  "Pirituba",
  "República",
  "Sacomã",
  "Santa Cecilia",
  "Santana",
  "Santo Amaro",
  "Saúde",
  "Sé",
  "Tatuapé",
  "Tremembé",
  "Tucuruvi",
  "Vila Andrade",
  "Vila Clementino",
  "Vila Leopoldina",
  "Vila Madalena",
  "Vila Mariana",
  "Vila Matilde",
  "Vila Olimpia",
  "Vila Prudente",
].sort((left, right) => left.localeCompare(right, "pt-BR"));
